# Generated by Django 4.2.5 on 2023-10-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_birthday',
            field=models.DateField(),
        ),
    ]
